### ISSUE TITLE
lmeds.l

### ISSUE THREAD

**Issue by garaemon** [euslisp/jskeus#153]
lmeds.lが欲しいです

**Comment by k-okada** [comment]
#169 で対応しました．いくつか抜いた関数があるのでこれでいいか確認してみてください．

**Comment by k-okada** [comment]
これがOKだったらeuslib/jsk からコピーした関数を消したらいいわけだけど，今使っているのはケンシロウ班かな．浅野くん大久保くんだろうか．ここ見ていますか〜
