### ISSUE TITLE
 dumpしたオブジェクトの(:handle-rarm-handle () handle0) で  forward-message-toをつける [sf#19]

### ISSUE THREAD

**Issue by k-okada** [euslisp/jskeus#17]
_This post was originally posted at http://sourceforge.net/p/jskeus/tickets/19_

(:handle-rarm-handle () handle0)
とダンプしているところを
(:handle-rarm-handle (&rest args) (forward-message-to handle0 args))
とダンプしてくれると使いやすいと思います．

**Comment by snozawa** [comment]
Done (https://github.com/euslisp/jskeus/issues/17#issuecomment-36506873)
