### ISSUE TITLE
両手で同じものを持った時のIK

### ISSUE THREAD

**Issue by YuOhara** [euslisp/jskeus#184]
右手と左手で同じ物体をもって，IKを解きたいです．（ドリルの両手持ちなど）
その際，ドリルの刃先などを:ｘとしてIKを解いたりしたいです．

サンプルコード等，どこかにあるでしょうか？

**Comment by k-okada** [comment]
https://github.com/euslisp/jskeus/blob/master/irteus/demo/dual-manip-ik.l
でしょうか．
https://github.com/euslisp/jskeus
2.1のサンプルはひと通り見ておくといいともいます．

--
◉ Kei Okada


2015-03-25 16:27 GMT+09:00 Yu Ohara <notifications@github.com>:

**Comment by YuOhara** [comment]
>https://github.com/euslisp/jskeus/blob/master/irteus/demo/dual-manip-ik.l
>でしょうか．

なるほど，確かにこれを参考にすればできそうです．ありがとうございます．

>https://github.com/euslisp/jskeus
>2.1のサンプルはひと通り見ておくといいともいます．

時間ができたら，全部見ておきます．
