### ISSUE TITLE
look-at-targetにcoordsを入れられるようにしたい [sf#21]

### ISSUE THREAD

**Issue by k-okada** [euslisp/jskeus#19]
_This post was originally posted at http://sourceforge.net/p/jskeus/tickets/21_

https://sourceforge.net/p/jsk-ros-pkg/code/4103/
にある，
+ (send pr2 :inverse-kinematics (send chair :handle)
+ :link-list (list
+ (send pr2 :link-list (send pr2 :larm :end-coords :parent))
+ (send pr2 :link-list (send pr2 :rarm :end-coords :parent)))
+ :move-target (list (send pr2 :larm :end-coords) (send pr2 :rarm :end-coords))
+ :look-at-target t
+ )
+ (send ri :ang
ですが，両手の真ん中，とか，対象物の先，をみるためにlook-at-targetにcoordsをいれてもいい気がしました．
いまはt/nilが想定されていそうです．

**Comment by snozawa** [comment]
Done (https://github.com/euslisp/jskeus/issues/19#issuecomment-36506859)
