### ISSUE TITLE
want to hide reference axes in irtviewer

### ISSUE THREAD

**Issue by YuyaNagamatsu** [euslisp/jskeus#205]
I want only to render euslisp robot models on irtviewer for illustrations in my papers or posters.

Is there any method to hide the reference axes in irtviewer, rather than translating the model and dragging the viewer to push out the axes ?

**Comment by k-okada** [comment]
you can use draw-origin option, 
https://github.com/euslisp/jskeus/blob/master/irteus/irtviewer.l#L75

try 
``` 
(make-irtviewer :draw-origin nil :draw-floor t)
```

**Comment by YuyaNagamatsu** [comment]
Thank you!
I got the axes hidden by (make-irtviewer :draw-origin nil) .

![with-axes](https://cloud.githubusercontent.com/assets/7259650/7491154/9e8c4e1c-f421-11e4-95b6-6f18e8afa992.png)
![wo-axes](https://cloud.githubusercontent.com/assets/7259650/7491157/a1d5d994-f421-11e4-880d-3a560b0e50a4.png)

**Comment by k-okada** [comment]
when we learn new thing, it is better update documentation, see https://github.com/euslisp/jskeus/pull/207/files for example and check 
http://euslisp-docs.readthedocs.org/en/latest/jskeus/jmanual/#_26 for document

**Comment by YuyaNagamatsu** [comment]
Oh, I'm seeing the web manual for the first time. I did'nt know it.

It's already written about this option?
Can I edit any other documentation?

**Comment by k-okada** [comment]
this option is not documented until
https://github.com/euslisp/jskeus/pull/207/files commit.

if you define function like
```
(defun hoge ()
  "this is document"
  (+ 1 2 3))
```
then that document string will appear on html or pdf, please find
"make-irtviewer" section on
http://euslisp.github.io/jskeus/jmanual-node174.html,
http://euslisp-docs.readthedocs.org/en/latest/jskeus/jmanual/#_26

Adding or editing new documentation is highly welcome.
https://github.com/euslisp/jskeus/commit/53cbce80963710ee1074ef8f9413999d7b58e13c
https://github.com/euslisp/jskeus/commit/a9bd7fa184621fa22afaaaf302002d7ab700bfd1


--
◉ Kei Okada

**Comment by YuyaNagamatsu** [comment]
I see.
When I find lack of documentation, I will make pull request.
