### ISSUE TITLE
ヤコビアンを計算する例のサンプルがほしい

### ISSUE THREAD

**Issue by yuki-asano** [euslisp/jskeus#218]
こちらもissue切っといてとのことだったので、切ります。

**Comment by snozawa** [comment]
こちらも、jacobian計算の例があるとよさそうですね。

**Comment by yuki-asano** [comment]
jmanualのp196あたりに、重心ヤコビアンの計算方法がばっちりかかれていて感動しました。

**Comment by snozawa** [comment]
よさそうなのでcloseします。
