### ISSUE TITLE
eusモデルに画像テクスチャを貼りたい

### ISSUE THREAD

**Issue by furushchev** [euslisp/jskeus#226]
以前古田先輩がやっていた気がするのですが。。。
コードなど参考になる部分があれば教えていただきたいです。

**Comment by snozawa** [comment]
https://github.com/euslisp/EusLisp/blob/master/models/room602-wheelchair-object.l
や
https://github.com/euslisp/jskeus/blob/master/irteus/test/read-img.l
でしょうか。

**Comment by furushchev** [comment]
出来ました！ありがとうございます！
