### ISSUE TITLE
irteusglの関数transparentでメモリーリーク

### ISSUE THREAD

**Issue by k-okada** [euslisp/jskeus#24]
_This post was originally posted at http://sourceforge.net/p/jskeus/tickets/26_

小島光晴です。

お世話になっています。

irteusglの関数transparentでopenglのdisplay listをきちんと開放していないためにメモリーリークが起きているようです。

テストプログラムとこちらで考えたパッチをお送りしますので、
ご検討のほどよろしくお願い致します。

**Comment by snozawa** [comment]
Done (https://github.com/euslisp/jskeus/issues/24#issuecomment-36506834)

**Comment by k-okada** [comment]
@furushchev https://github.com/euslisp/jskeus/commit/049747d377d86c4282562b746213cdd2cc07388e#diff-9668ec815fcfd18a7ca0cfa219ca53a7 が修正パッチのようです．
