### ISSUE TITLE
Proposal of new documentation string usage.

### ISSUE THREAD

**Issue by snozawa** [euslisp/jskeus#253]
Moved from https://github.com/euslisp/jskeus/pull/243.

In addition, how about new printing usage style (which is not included in PR)?

```
;; New style
(defun demo-function ()
  "demo function"
  ...
)
(warn "(demo-function) ;; ~A~%" (documentation 'demo-function)) ;; Use documentation string
```

instead of
```
;; Old style
(defun demo-function ()
  "demo function"
  ...
)
(warn "(demo-function) ;; demo function~%")
```
Using new style, we can reduce almost same string for documentation string and print message.

**Comment by k-okada** [comment]
+1

--
◉ Kei Okada

**Comment by snozawa** [comment]
Thanks.
If documentation string is too long and include newlines, this method cannot be used.
However, most of demo function documentation is small and this method can be used.
