### ISSUE TITLE
:calc-zmpの挙動が時々不安定になる

### ISSUE THREAD

**Issue by garaemon** [euslisp/jskeus#329]
モデルはhrp2jskntを利用.

以下のようにzmpの値が突然大きくなることがあります。
プロットしているのは:calc-zmpのx, yの値です

![screenshot from 2015-12-28 20 25 44](https://cloud.githubusercontent.com/assets/40454/12018039/47a21b74-ada1-11e5-96ba-9e4424cbce10.png)

テストコード
https://gist.github.com/garaemon/104d2dee4736754992ab

**Comment by garaemon** [comment]
:dt の値によって挙動が変わってくるように見えます

**Comment by snozawa** [comment]
robotは何ですか？

**Comment by snozawa** [comment]
ごめん、hrp2jskntでしたね。

**Comment by snozawa** [comment]
多分calc-zmpに入力される速度加速度が不連続になっています。
まず補間がlinear-interpolatorだとその変化点で加速度が過大になるので、
minjerk-interpolatorにしてください。
次は、:move-centroid側の問題っぽいのですが、:min-loop 2を:min-loop 3にしてみてくれますでしょうか。

**Comment by garaemon** [comment]
minjerk + :min-loop 3で挙動が良くなりました

![image](https://cloud.githubusercontent.com/assets/40454/12030579/496bc47a-ae44-11e5-95e7-4c63dee00eb2.png)
