### ISSUE TITLE
:calc-zmpの引数に速度や加速度をオプションとして与えたい

### ISSUE THREAD

**Issue by terasawa** [euslisp/jskeus#331]
:calc-zmpの内部でトルクを計算しているところがあり、現在はその計算で必要な速度・加速度はdtから計算されるようになっていると思いますが、
最適化による動作生成時の制約条件式に用いるときなど、速度や加速度の真値を直接与えたい時があるので、zmpを計算したいその時々の速度や加速度が直接計算できるときは（dtから計算するものではなく）真値を与えられるようにしたいです。

**Comment by snozawa** [comment]
> 最適化による動作生成時の制約条件式に用いるときなど、速度や加速度の真値を直接与えたい時があるので、zmpを計算したいその時々の速度や加速度が直接計算できるときは（dtから計算するものではなく）真値を与えられるようにしたいです。

ちなみに，最適化計算からあからは速度・加速度の他位置の情報もでてきますか？
であれば，位置の情報を渡して上げる現状の使い方で使えたりしませんか？

また，直接最適化計算から計算されるのが速度・加速度だとして，
通常はそれを積分して角度までだすことがあると思うので，
その値を入れるのはどうでしょうか．
