### ISSUE TITLE
make-cube で作った直方体のモデルに利用できるメソッドを知りたいです．

### ISSUE THREAD

**Issue by kochigami** [euslisp/jskeus#347]
一度作った直方体の辺の長さを返すメソッドはありますか．
ドキュメントでどのように検索すれば出てくるか分かりませんでした．申し訳ございません．
```
(setq bx (make-cube 10 20 30))
(send bx :pose) ;;座標
(send bx :dimension) ;; 3 次元
(send bx :width) ;;できない
```

**Comment by k-okada** [comment]
send bx :methods

--
◉ Kei Okada


2016-03-09 23:11 GMT+09:00 Kanae Kochigami <notifications@github.com>:

**Comment by kochigami** [comment]
ありがとうございます．初歩的ですみません．
