### ISSUE TITLE
Failing jobs on Kinetic build farm

### ISSUE THREAD

**Issue by jacquelinekay** [euslisp/jskeus#360]
The Kinetic release for jskeus fails on the buildfarm for multiple platforms:

http://build.ros.org/job/Kbin_uX32__jskeus__ubuntu_xenial_i386__binary/
http://build.ros.org/job/Kbin_arm_uXhf__jskeus__ubuntu_xenial_armhf__binary/
http://build.ros.org/job/Kbin_uW32__jskeus__ubuntu_wily_i386__binary/

When the maintainers have a moment, can they look into these reason behind these failures to see if it's fixable in code or by adding a rosdep key?

**Comment by k-okada** [comment]
thanks, wip in https://github.com/euslisp/EusLisp/pull/171

--
◉ Kei Okada

**Comment by k-okada** [comment]
Hope jsk-ros-pkg/jsk_roseus/pull/436 will fix this.

**Comment by jacquelinekay** [comment]
Yes, it looks good now. Thank you!

**Comment by k-okada** [comment]
thanks.

--
◉ Kei Okada
