### ISSUE TITLE
kinematics viewer が上がってるとcoordsがdraw-onされない

### ISSUE THREAD

**Issue by YuOhara** [euslisp/jskeus#401]
kinematics viewer ありだと
(send (make-coords) :draw-on :flush t) 
が上手く動かない気がします。

```
(load "package://hrpsys_ros_bridge_tutorials/euslisp/samplerobot-interface.l")
;; (SampleRobot)
(make-irtviewer)
(send (make-coords) :draw-on :flush t) ;; able to see
(read-line)
(samplerobot-init)
;; (objects *sr*)
(send (make-coords) :draw-on :flush t) ;; not able to see
```

**Comment by mmurooka** [comment]
`(send (make-coords) :draw-on :flush t :viewer (send *irtviewer* :view))`
ではどうだろう．

**Comment by YuOhara** [comment]
やっぱり見えないです・・
```
(send (make-coords) :draw-on :flush t :viewer (send *irtviewer* :viewer))
```

**Comment by k-okada** [comment]
please try https://github.com/euslisp/jskeus/pull/402

**Comment by YuOhara** [comment]
Thanks. It worked.

**Comment by k-okada** [comment]
draw-on 系はよく使っているかな？
ちょっと使ってみて、副作用がないか教えてもらえると嬉しいです．

メモ：
各 draw-on で:flush t のときだけ、viewerをmake-currentするようにした．なので、
send a :draw-on
send b :draw-on
send c :draw-on :flush t
はだめなはず．やっぱ全ての場合でmake-currentするべきか．

--
◉ Kei Okada


2016-12-02 19:54 GMT+09:00 Yu Ohara <notifications@github.com>:

**Comment by YuOhara** [comment]
はい。私はcascoordsを新しく作ってdraw-onするなど使っていました。
しばらく使ってみます。
