### ISSUE TITLE
*irtviewer*のchange-backgroundでkinematic simulatorの色が変わる

### ISSUE THREAD

**Issue by pazeshun** [euslisp/jskeus#404]
IRT viewerとkinematic simulatorを両方上げた状態で、
```
(send *irtviewer* :change-background #f(1 1 1)
```
とすると、kinematic simulatorの方の背景色が変わります。

**Comment by pazeshun** [comment]
BaxterとHRP2の場合で確認しました

**Comment by YoheiKakiuchi** [comment]
まったくのカンなのですが、
https://github.com/euslisp/jskeus/issues/401
と同じ問題ではないでしょうか。

https://github.com/euslisp/jskeus/blob/master/irteus/irtviewer.l#L301-L304
このメソッドのglの関数の前に、以下を足すと良かったりしないでしょうか。
~~~
(send vs :makecurrent)
~~~
