### ISSUE TITLE
jskeusのjmanualのbuild方法について

### ISSUE THREAD

**Issue by rkoyama1623** [euslisp/jskeus#422]
#419 に関連して，ドキュメントの生成方法について質問です．

手元のPCでeuslispとjskeusを最新にして，ドキュメント生成を試みると
```bash
$ cd jskeus/doc
$ make
exit
mkdir -p /tmp/user/1000/tmp.7DcmXn2U9J/fig
cp ../eus/doc/jlatex/*.tex /tmp/user/1000/tmp.7DcmXn2U9J
cp: `../eus/doc/jlatex/*.tex' を stat できません: そのようなファイルやディレクトリはありません
make: *** [copy_eus_tex] エラー 1
```
となってしまいます．
どこかのバージョンまでは，`jskeus/eus`というeuslispのコピーと思われるディレクトリが（おそらくcatkin build 実行時に）自動で生成されていたと思うのですが，現在は生成されないためbuildに失敗しているように見えます．

jskeusのドキュメントの生成方法は現在，どのようになっているでしょうか？

**Comment by k-okada** [comment]
あ、これはcatkinはつかわず
```
$ hub clone euslisp/jskeus
$ cd jskeus/
$ make
$ make doc
```
とすることが想定されていました．

--
◉ Kei Okada


2017年3月15日 18:14 Ryo KOYAMA <notifications@github.com>:

**Comment by rkoyama1623** [comment]
教えていただいた方法でbuildできました．
ありがとうございました．
