### ISSUE TITLE
joint-min-max-tableを作るプログラムが欲しい [sf#52]

### ISSUE THREAD

**Issue by k-okada** [euslisp/jskeus#50]
_This post was originally posted at http://sourceforge.net/p/jskeus/tickets/52_

http://sourceforge.net/p/jskeus/tickets/43/
でjoint-min-max-tableがサポートされたので、
それを作成するプログラムが欲しいとおもいました。

**Comment by snozawa** [comment]
joint-min-max-table generation is supported.
