### ISSUE TITLE
[irtrobot.l] :calc-static-balance-pointの:moment-list:force-listの計算の符号が違う

### ISSUE THREAD

**Issue by ykawamura96** [euslisp/jskeus#540]
:calc-static-balance-pointの引数の、force-listとmoment-listですが、実装を見ると
force-list: ロボットが受ける力
moment-list: ロボットが与えるモーメント
となっているようです。

@Naoki-Hiraoka さん、補足お願いします。

**Comment by Naoki-Hiraoka** [comment]
I think this issue is solved by 
https://github.com/euslisp/jskeus/pull/541
